/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'denger' at '15-10-28 下午12:26' with Gradle 2.6
 *
 * @author denger, @date 15-10-28 下午12:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
